Upgrade Payoneer payment service
topcoder-platform/tc-website pull request #71
Opened 2022-12-22 01:42 UTC by hamidre13

2022-12-22 01:55 UTC, kkbattatc requested changes

2022-12-22 01:55 UTC, kkbattatc commented on src/main/com/topcoder/web/tc/controller/PayoneerService.java
> +      String link = new JSONObject(res.get("result").toString()).get("registration_link").toString();
please do an not empty check and return accordingly

2022-12-22 01:55 UTC, kkbattatc commented on src/main/com/topcoder/web/tc/controller/PayoneerService.java
> +      }
make this an if-else-if

2022-12-22 01:55 UTC, kkbattatc commented on src/main/com/topcoder/web/tc/controller/PayoneerService.java
> +      if (body != "") {
better to use StringUtils.isEmpty(String str)

2022-12-22 01:55 UTC, kkbattatc commented on src/main/com/topcoder/web/tc/controller/PayoneerService.java
> +      JSONObject obj = new JSONObject(result);
I think you need to handle json decoding exception

2022-12-22 07:48 UTC, eisbilir requested changes

2022-12-22 07:48 UTC, eisbilir commented on src/main/com/topcoder/web/tc/controller/PayoneerService.java
> +  private static String getApplicationToken() throws Exception {
It's better to cache the token and check the expire date before reusing it instead of making a new token request for each operation.

2022-12-22 15:57 UTC, hamidre13 commented on src/main/com/topcoder/web/tc/controller/PayoneerService.java
> +  private static String getApplicationToken() throws Exception {
I agree but I did not know the pattern in java would you help with that?

2022-12-22 17:20 UTC, eisbilir commented on src/main/com/topcoder/web/tc/controller/PayoneerService.java
> +  private static String getApplicationToken() throws Exception {
The response has "expires_in" field. https://developer.payoneer.com/docs/mass-payouts-v4.html#/9514e3ef96c62-requesting-an-application-token
`expires_in | int | The time period (in seconds) for which the access token is valid. (Tokens are typically granted for a period of 30 days)`
Using that value you can calculate the expiration date and store it in a variable along with access_token. It's good to set expiration date as 10 minutes before actual expiration date.
And your getApplicationToken() method can compare current date and expiration date. Based on that comparison, you either generate new token or return the cached token.
In order to make it guaranteed; if we have an invalid/expired token error at any time then we also need to refresh the cached token.

2022-12-22 20:57 UTC, rakibansary commented on src/main/com/topcoder/web/tc/controller/PayoneerService.java
> +  private static Document getXMLResponse(String baseApiUrl, Map<String, String> parameters) throws Exception {
Let's remove this. This is a `private static` method and is definitely not used outside of this class.

2022-12-22 20:58 UTC, rakibansary commented on src/main/com/topcoder/web/tc/controller/PayoneerService.java
> +  public static String xmlToString(Node node) {
Let's remove this piece of unused code as well.

2022-12-22 21:00 UTC, rakibansary requested changes

2022-12-22 21:00 UTC, rakibansary commented on src/main/com/topcoder/web/tc/controller/PayoneerService.java
> +  public static double getBalanceAmount() throws PayoneerServiceException {
Let's remove this - or atleast comment this out with a log. getBalanceAmount() returns entire topcoder balance and is not relevant here

2022-12-26 13:00 UTC, eisbilir approved these changes

2022-12-26 20:09 UTC, merged